#!/bin/sh
# =============================================================================
# render-frontend-env.sh — Lê segredos do Vault e gera .env.vault-frontend
#
# Executa no servidor Hetzner antes de subir o frontend em produção.
# Requer que o Vault do backend já esteja inicializado e desbloqueado.
#
# Pré-requisitos:
#   - Vault rodando em http://vault:8200 (rede Docker ipysy-net)
#   - VAULT_TOKEN com permissão de leitura em secret/ipysy/*
#
# Uso:
#   VAULT_ADDR=http://vault:8200 VAULT_TOKEN=<token> sh scripts/vault/render-frontend-env.sh
#
# Ou via Docker na mesma rede do backend:
#   docker run --rm --network ipysy-net \
#     -e VAULT_ADDR=http://vault:8200 \
#     -e VAULT_TOKEN=<token> \
#     -v $(pwd)/vault-runtime:/vault-runtime \
#     hashicorp/vault:latest \
#     sh /scripts/render-frontend-env.sh
# =============================================================================

set -e

VAULT_ADDR="${VAULT_ADDR:-http://vault:8200}"
RUNTIME_FILE="${RUNTIME_FILE:-vault-runtime/.env.vault-frontend}"

echo "=== IPYSY Frontend — Vault Render ==="
echo "Vault: ${VAULT_ADDR}"

# Aguarda Vault estar disponível
until vault status > /dev/null 2>&1; do
  echo "Aguardando Vault..."
  sleep 2
done
echo "Vault disponível."

# -----------------------------------------------
# Seed do grupo frontend (idempotente)
# Cria o path secret/ipysy/frontend se não existir
# -----------------------------------------------
OTEL_DEFAULT="http://signoz-otel-collector:4317"

if ! vault kv get secret/ipysy/frontend > /dev/null 2>&1; then
  echo "  Criando secret/ipysy/frontend com valores padrão..."
  vault kv put secret/ipysy/frontend \
    OTEL_ENDPOINT="${OTEL_DEFAULT}" \
    OTEL_SERVICE_NAME="ipysy-frontend"
  echo "  Criado. Atualize OTEL_ENDPOINT se necessário:"
  echo "  vault kv patch secret/ipysy/frontend OTEL_ENDPOINT=<endereço-real>"
else
  echo "  secret/ipysy/frontend já existe — preservando valores atuais."
fi

# -----------------------------------------------
# Lê segredos do Vault
# -----------------------------------------------
echo "Lendo segredos do Vault..."

OTEL_ENDPOINT=$(vault kv get -field=OTEL_ENDPOINT secret/ipysy/frontend)
OTEL_SERVICE_NAME=$(vault kv get -field=OTEL_SERVICE_NAME secret/ipysy/frontend)

# -----------------------------------------------
# Gera o arquivo de runtime
# -----------------------------------------------
mkdir -p "$(dirname "$RUNTIME_FILE")"

cat > "$RUNTIME_FILE" <<EOF
# ============================================================================
# AUTO-GENERATED by render-frontend-env.sh — NÃO EDITAR MANUALMENTE
# Source: HashiCorp Vault (secret/ipysy/frontend)
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Para atualizar: vault kv patch secret/ipysy/frontend CHAVE=valor
#                 e re-executar este script
# ============================================================================

# OpenTelemetry / SigNoz (server-side apenas — nunca exposto ao browser)
OTEL_ENDPOINT=${OTEL_ENDPOINT}
OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
EOF

echo "=== Render concluído: ${RUNTIME_FILE} ==="
